# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ssKwa4wYpy2SYGh6Vy5wNdUIFzNY_YVx
"""

#Problema 2  / 7 ptos x4 pruebas / 28 puntos
#Ingreso de valores en árbol TRI-nario
#---------------------------------------------------------------------------------
#Confeccione un programa que lea varios números y cree un árbol trinario con listas
# esto es igual que el binario, pero los elementos que son iguales van en una lista
# centro, de la forma [numero, [subarbol IZQ], [mismo NUM], [subarbol DER] ]
#---------------------------------------------------------------------------------
#Ejemplo de entrada:
#         20 30 90 90 8 5 90
#La salida debe ser
#         [20, [8, [5, [], [], []], [], []], [], [30, [], [], [90, [], [90, [], [90, [], [], []], []], []]]]
#[120, [], [120, [], [120, [], [], []], []], []]
#[120, [], [120, [], [120, [], [], []], []], []]
#Árbol binario con listas
class ArbolTrinario:
    def __init__(self, numero):
        self.numero = numero
        self.hijos = [[], [], []]  # Izquierda, Centro, Derecha

    def insertar(self, numero):
        if numero < self.numero:
            if not self.hijos[0]:
                self.hijos[0] = ArbolTrinario(numero)
            else:
                self.hijos[0].insertar(numero)
        elif numero > self.numero:
            if not self.hijos[2]:
                self.hijos[2] = ArbolTrinario(numero)
            else:
                self.hijos[2].insertar(numero)
        else:
            if not self.hijos[1]:
                self.hijos[1] = ArbolTrinario(numero)
            else:
                self.hijos[1].insertar(numero)

    def imprimir(self):
        return [self.numero, self.hijos[0].imprimir() if self.hijos[0] else [],
                self.hijos[1].imprimir() if self.hijos[1] else [],
                self.hijos[2].imprimir() if self.hijos[2] else []]


def leer_numeros():
    numeros = input().split()
    return [int(numero) for numero in numeros]


numeros = leer_numeros()
arbol = ArbolTrinario(numeros[0])
for numero in numeros[1:]:
    arbol.insertar(numero)

print(arbol.imprimir())