# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ssKwa4wYpy2SYGh6Vy5wNdUIFzNY_YVx
"""

#Problema 1  / 8 ptos x4 pruebas / 32 puntos
#Concatenación de listas o tuplas
#--------------------------------
#Confeccione un programa que lea 2 tuplas sean t1 y t2
#La salida debe ser una tupla en el orden t2 t1 t2
#---------------------------------
#Ejemplo de entrada:
#         20 90 hola
#		  mundo 44
#La salida debe ser
#         ('mundo', 44, 20, 90, 'hola', 'mundo', 44)
t1 = input().split()
t2 = input().split()

t1 = [int(x) if x.isdigit() else x for x in t1]
t2 = [int(x) if x.isdigit() else x for x in t2]
t3 = tuple(t2 + t1 + t2)

print(t3)